from typing import Protocol
from app.domain.model.article import Article


class ArticleRepository(Protocol):
    def save(self, article: Article) -> Article: ...

    def find_by_id(self, article_id: int) -> Article | None: ...

    def find_all(self) -> list[Article]: ...

    def delete(self, article_id: int) -> None: ...
