default:
  target: duckdb
  outputs:
    postgres:  
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: jaffleshop
      schema: dbt
      threads: 12
  outputs:
    duckdb:
      type: duckdb
      path: ./data/dev.duckdb
      schema: main
      threads: 4