services:
  db:
    image: postgres:latest  # or postgres:18
    container_name: kapp_dev_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kapp_db
    volumes:
      - ./postgres:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql